# Generated by Django 3.0.14 on 2022-06-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayush', '0002_auto_20220623_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_log',
            name='last_logout',
            field=models.DateTimeField(),
        ),
    ]
