# Generated by Django 3.0.14 on 2022-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayush', '0005_auto_20220624_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_description',
            field=models.CharField(max_length=1000),
        ),
    ]
