# Generated by Django 3.0.14 on 2022-06-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayush', '0009_password_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_log',
            name='last_logout',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
